name: Playwright Tests
# This workflow runs E2E tests using Playwright on every pull request.

on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    permissions:
      pull-requests: write
      deployments: write
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Generate and Update Snapshots
      run: npx playwright test --update-snapshots
    - name: Run Playwright tests
      run: npx playwright test
    - name: Upload Report on Failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Upload Snapshots on Failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-snapshots-linux
        path: tests/**/*.ts-snapshots/
        retention-days: 7
    - name: Publish to Cloudflare Pages
      if: always()
      uses: cloudflare/pages-action@v1
      id: publish_report
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME_E2E }}
        directory: playwright-report
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}

    - name: Fail if report deployment failed
      if: steps.publish_report.outputs.url == ''
      run: |
        echo "::error::Cloudflare Pages deployment failed to produce a URL."
        exit 1

    - name: Publish test report comment
      if: always()
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: '📊 **Playwright Test Report:** [View Report](${{ steps.publish_report.outputs.url }})'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
